///////////////////////////////////////////////////////////
//  Pinguino.cs
//  Implementation of the Class Pinguino
//  Generated by Enterprise Architect
//  Created on:      20-may.-2017 12:36:44 p. m.
//  Original author: user
///////////////////////////////////////////////////////////

public class Pinguino : AveNoVoladora {

	public Pinguino()
    { 
	}

}//end Pinguino