///////////////////////////////////////////////////////////
//  Ave.cs
//  Implementation of the Class Ave
//  Generated by Enterprise Architect
//  Created on:      20-may.-2017 12:36:41 p. m.
//  Original author: user
///////////////////////////////////////////////////////////

public class Ave {

    // Properties

    private string _color;

    public string getColor()
    { 
        return _color; 
    }


    public void setColor (string value)
    { 
        _color = value; 
    }

    // Construct 

    public Ave()
    {
    }
}//end Ave