///////////////////////////////////////////////////////////
//  AveNoVoladora.cs
//  Implementation of the Class AveNoVoladora
//  Generated by Enterprise Architect
//  Created on:      20-may.-2017 12:36:42 p. m.
//  Original author: user
///////////////////////////////////////////////////////////

public class AveNoVoladora : Ave {

	public AveNoVoladora()
    {
	}

}//end AveNoVoladora