///////////////////////////////////////////////////////////
//  Gorrion.cs
//  Implementation of the Class Gorrion
//  Generated by Enterprise Architect
//  Created on:      20-may.-2017 12:36:43 p. m.
//  Original author: user
///////////////////////////////////////////////////////////

public class Gorrion : AveVoladora {

	public Gorrion()
    {
	}

}//end Gorrion